SET IDENTITY_INSERT [dbo].[Subcategories] ON
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (1, N'Автомобильные', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (2, N'Железнодорожные', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (3, N'Крановые', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (4, N'Лабораторные', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (5, N'Медицинские', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (6, N'Настольные', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (7, N'Промышленные', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (8, N'С печатью этикеток', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (9, N'Товарные', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (10, N'Торговые', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (11, N'Весы-регистраторы', 1, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (12, N'Терминалы', 2, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (13, N'Фискальные регистраторы', 2, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (14, N'Счетчики банкнот', 3, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (15, N'Счетчики монет', 3, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (16, N'Деткторы банкнот', 3, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (17, N'Начальный класс', 4, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (18, N'Средний класс', 4, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (19, N'Промышленный класс', 4, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (20, N'Мобильные принтеры', 4, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (21, N'Системы взвешивания и маркировки', 4, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (22, N'Сканеры', 5, null)
INSERT INTO [dbo].[Subcategories] ([SubcategoryID], [Name], [CategoryID], [ImageID]) VALUES (23, N'Терминалы', 6, null)
SET IDENTITY_INSERT [dbo].[Subcategories] OFF